name: GithubActions_Secrets
on: push
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Run Single line 
        run: |
          echo ${{secrets.USER_NAME}}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $PASSWORD
        env:
          PASSWORD: ${{secrets.PASSWORD}}
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script using if condition
        run: |
        
          if [ "$PASSWORD" == "Alaguraja00" ]
          then          
            echo "Got Secret"
          fi
        env:
          PASSWORD: ${{secrets.PASSWORD}}
